### ISSUE TITLE
Epic Planning: What do we need to do to integrate Statviz into Boxtribute?

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxtribute#1093]
## Goal 1: make statviz dashboard appear in Boxtribute v2 and make only download of svg or png/jpeg possible
Therefore we need to
- create route for dashboard
- import components from statviz in Boxtribute
- write loader which is checking auth and pre-fetching data
- query visualization data from read-only replica and not from normal sql db

#### Open Questions:
- What permissions are needed to see visualizations? What permissions are needed to download visualizations?
- Should a csv be downloadable?
- What styling options do we enable? Hide/Show Title, height & width? background? colors? fonts? borders?

## Goal 2: visualizations can be shared via private links to other Boxtribute users
In the case of private link sharing, I strongly recommend to only generate a link with the filter and styling parameters in the url and the whole visualization is build from scratch when the link is accessed.

#### Open questions are:
- Regarding styling: should style be editable in the newly created link? styling done through url parameters?
- Regarding interaction: should there be interactions for filtering and grouping in the shared link?

#### Open product questions are:
- Who should have permissions to share public links?
- How long should the link last? If the link lasts forever we might run into problems with server space. Links and data should most likely be automatically deleted and the user should be warned from the generation on that links are only temporary.
- Regarding interaction: should there be interactions for filtering and grouping in the shared link? should they always be disabled or something inbetween? Do we need options to enable what interactions are possible when creating the shared link? 
- Regarding styling: should style be editable in the newly created link?

#### ---> open technical question: 
- Regarding underlying data: Either we store the query parameters or we store the data cube or the svg. Which one should we store when the share button is pressed and where?

**Comment by HaGuesto** [comment]
@aerinsol @pylipp @seinig @MaikNeubert maybe have quick read. We should have a discussion call for Goal 2 and 3 during the hackathon to clarify a bit the requirements from the product side and we can say form the Tech side what is feasible.

**Comment by seinig** [comment]
Update after discussion with @aerinsol 
## Goal 1
- we agree on that and it's already in process
- downloading individual viz without bulk download is a fine start

#### Update Concerning Open Questions:
- Permission to see and to download can be the same; (seeing enables screenshotting as pointed out by @pylipp )

## Goal 2

#### We split that up into 

## 2.1. visualizations can be shared via private links to other Boxtribute users *within the same boxtribute base*

- this is already doable as @Maik stores variables for filtering in URL
- Use Case already exists insofar as it directly affects the user workflow within a single base: i.e. 1. Logistics coordinator dials in significant settings for specific viz 2. shares it to PR coordinator for publication across platforms in context of narratives for public impact (i.e. "these are the top products we ship & therefore need, please donate more of these items"...) 
- in this way it partly answers the open question on the specific workflow on the user side

#### Next Steps
- finish on FE side
#### Open Questions
- is authorization management needed here?

## 2.2.  visualizations can be shared via private links to other Boxtribute users *across different boxtribute bases*
#### Next Steps
- create viz with according to use case, that is [5th viz](https://github.com/boxwise/boxtribute/issues/932) sunburst chart showing inStock items ('delivering base shares current stock to receiving base in order to show them what could be prepared for shipment')
- get aligned on BE-FE interaction

#### Open questions
- how to manage authorization (i.e. enabled between users of bases that have a shipping agreement)

## Goal 3
we cancelled the method of snapshotting datacubes/SVGs for public sharing as this still means too much effort for too few of an benefit:
- public sharing in general is a challenge in terms of security, needs research
- snapshotting means there won't be live data; static data can already be published via Goal 1. (multiplied by 2.2.) by down- & uploading certain curated viz'

#### We shifted this goal and split it up into 
## 3.1. direct public sharing/embedding of fully functional viz/datacubes
 
- only brings a significant benefit with live data (see above)
- turns out as out of scope for this project (due to security issues)
- not only was a desideratum for this project but is also crucial to other projects ahead (availability mapping; 'which NGO at what base located where has which items in stock?'), therefore:

#### Next Up
- formulate programming challenge:
- for public sharing of live data
- public embedding of viz relying on live data
- how to manage authorization flow between FE and BE
(- how to make filtering possible in the embedded viz relyig on live data)
- communicate this issue in the DSEE community
- include this issue in the final report on the 100xDigital project (@seinig )

## 3.2. simplified version of 3.1.: public embedding of live data in format 'single number'
- this might be still in scope of this project

#### Open Questions
- how to realize this in a secure way
- athorization management: i.e. 'head of operations' of certain base can agree & withdraw their agreement on sharing single number live data (on website)
- manage agreement concerning different 'single numbers' data

possible data to start with
- boxes/items currently in stock (as on boxtribute-base landing page)
- boxes/items shipped out so far (or within the last year...) (priority)
- boxes/items created so far ...
- beneficaries currently 'active' ...

**Comment by pylipp** [comment]
# Goal 1
What permissions are needed to see visualizations? What permissions are needed to download visualizations?
- FE needs to enforce `view_inventory` to view stock-related graphs, and `manage_beneficiaries` to view beneficiary-related graphs (@aerinsol this means a Warehouse volunteer can't see beneficiary graphs but a Freeshop volunteer can see both beneficiary and inventory graphs)
- BE needs to enforce beneficiary/tag_relation read-RBP for beneficiary data, and the ones derived from `view_inventory` ABP for stock data

**Comment by aerinsol** [comment]
Wanted to say that instead of the actual implementation of 3.1 live sharing
with the public, we agreed that a DESIRED OUTCOME should be a write up that
clearly summarizes the security concerns and technical challenges. This can
be in German (should be fairly straightforward to translate into English
later if needed.)

Philipp, your understanding of the proposed permissions is correct :)

**Comment by HaGuesto** [comment]
@seinig Here, a break-down of actual tasks we need to release (infra-structure related) the different goals:

## Goal 1:
### must have:
- [Boxtribute FE] Implement routes (set the url address) and authorization in Boxtribute @HaGuesto #tiny
- [Boxtribute FE / Dropapp ] Update Menues to show links to visualizations @HaGuesto  #tiny
- [shared] create infra-structure to use shared components in both Boxtribute and Statviz @HaGuesto  #medium
- [Statviz FE / shared] move visualizations over to be shared components @MaikNeubert #medium
- [Boxtribute FE] import shared components in prepared route @HaGuesto #small

### nice to have:
- [Boxtribute BE] finish read-only replica set-up (e.g. update CI process) @pylipp 
- [all apps] some hygiene on linting, formatting, typescript, package mgmt. @HaGuesto 

## Goal 2.1:
nothing extra needed for releasing / infra-structure

## Goal 2.2:
- align first on requirements what is needed to show sunburst to other organisations before we do more palnning

**Comment by pylipp** [comment]
@HaGuesto re goal 2.2 I made a proposal [on Slack](https://boxwise.slack.com/archives/C04QEFG4V35/p1700061999315009) some days ago that noone objected against in the last SU. The implementation is ready for review in [this PR](https://github.com/boxwise/boxtribute/pull/1113).

**Comment by pylipp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [2.0 EPIC: public sharing of embedded viz and/or single number data](https://trello.com/c/TkDc1GHV/1384-20-epic-public-sharing-of-embedded-viz-and-or-single-number-data)

**Comment by pylipp** [comment]
Superceded [by this](https://github.com/boxwise/boxtribute/blob/master/docs/auth/public_sharing_of_statistics.md).
