### ISSUE TITLE
[C / 3rd viz] FE add interactions (e.g. filters) to viz

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxtribute#907]

**Comment by aerinsol** [comment]
Note: In spite of the title, we agreed to postpone generalizing filters with @HaGuesto @MaikNeubert @seinig  ( @seinig maybe worth updating the title here to match)

**Comment by aerinsol** [comment]
@MaikNeubert , since you're starting on the 3rd viz task of pie chart, what we discussed with @seinig was that the ideal would be something like the pie chart here: https://docs.google.com/spreadsheets/d/1JE2Of1Yj_pd3_JAsIHxivkBxT7PQmpd8Cxb15Fn7jJo/edit?usp=sharing

You can do it for current inventory for HERMINE rather than distributed items as shown here. 

Stretch goal would be displaying side-by-side with the top rankings.
